version: "3"
services:
  app:
    build:
      context: ./djangomysql
      dockerfile: Dockerfile
    entrypoint: ["./wait.sh"]
    depends_on: #links:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:latest
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
